ignore_missing_fields = true

theme = "rose-pine-moon"
transparent_background = true

cd_on_quit = true # needs the spf() wrapper in zsh/conf.d/50-aliases.zsh
zoxide_support = true
auto_check_update = false
